# Generated by Django 4.2.4 on 2023-11-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('contacts', models.ManyToManyField(related_name='contact_events', to='contact.contact')),
            ],
        ),
    ]
